---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(naniar)

convertTime = function(time) {
  timePieces = strsplit(time, ":")
  timePieces = sapply(timePieces, as.numeric)
  sapply(timePieces, function(x) {
    if (length(x) == 2) x[1] + x[2]/60
    else 60*x[1] + x[2] + x[3]/60
  })
}

findColLocs = function(spacerRow) {
  
  # starting indexes of columns
  spaceLocs = gregexpr(" ", spacerRow)[[1]]
  rowLength = nchar(spacerRow)
  
  if (substring(spacerRow, rowLength, rowLength) != " ")
    return( c(0, spaceLocs, rowLength + 1))
  else return(c(0, spaceLocs))
}

selectCols = function(shortColNames, headerRow, searchLocs) {
  sapply(shortColNames, function(shortName, headerRow, searchLocs){
    startPos = regexpr(shortName, headerRow)[[1]]
    if (startPos == -1) return( c(NA, NA) )
    index = sum(startPos >= searchLocs)
    #below is the change
    c(searchLocs[index] + 1, searchLocs[index + 1])
  }, headerRow = headerRow, searchLocs = searchLocs )
}

extractVariables = function(file,varNames =c("name", "home", "ag", "gun",
                                              "net", "time")) {
  
  
  # Find the index of the row with =s
  eqIndex = grep("^===", file)
  
  if(is_empty(eqIndex)) {
    headerRow = tolower("PLACE NUM   NAME                  AG HOMETOWN           NET     GUN")
    spacerRow ="===== ===== ===================== == ================== ======= ======="
    body = file
  } else {
  # Extract the two key rows and the data 
  spacerRow = file[eqIndex] 
  headerRow = tolower(file[ eqIndex - 1 ])
  body = file[ -(1 : eqIndex) ]
  }
  # I added this part to correct some issues happening in the women files, but it shouldn't affect the men files
  headerRow = gsub('hometown',
                   'home    ', headerRow)
  headerRow = gsub('gun tim',
                   'gun    ', headerRow)
  headerRow = gsub('net tim',
                   'net    ', headerRow)

  
  # Remove footnotes and blank rows
  footnotes = grep("^[[:blank:]]*(\\*|\\#)", body)
  if ( length(footnotes) > 0 ) body = body[ -footnotes ]
  blanks = grep("^[[:blank:]]*$", body)
  if (length(blanks) > 0 ) body = body[ -blanks ]
  
  
  # Obtain the starting and ending positions of variables   
  searchLocs = findColLocs(spacerRow)
  
  ## 2006 has an issue with the column locations
  if (grepl("2006",file[4])) searchLocs <- c(0,6,15,22,45,48,64,72,80,81,87,89)
  
  locCols = selectCols(varNames, headerRow, searchLocs)
  
  Values = mapply(substr, list(body), start = locCols[1, ], 
                  stop = locCols[2, ])
  colnames(Values) = varNames
  
  return(Values)
}

createDF = function(Res, year, sex) {
  # Determine which time to use
  if ( !is.na(Res[1, 'net']) ) useTime = Res[ , 'net']
  else if ( !is.na(Res[1, 'gun']) ) useTime = Res[ , 'gun']
  else useTime = Res[ , 'time']
  
  # Remove # and * and blanks from time
  useTime = gsub("[#\\*[:blank:]]", "", useTime)
  runTime = convertTime(useTime[ useTime != "" ])
  
  # Drop rows with no time
  Res = Res[ useTime != "", ]
  
  Results = data.frame(year = rep(year, nrow(Res)),
                       sex = rep(sex, nrow(Res)),
                       name = Res[ , 'name'], home = Res[ , 'home'],
                       age = as.numeric(Res[, 'ag']), 
                       runTime = runTime,
                       stringsAsFactors = FALSE)
  invisible(Results)
}
```

```{r}
## I would reccommend setting this to your working directory
setwd("C:/Users/William/OneDrive/MSDS_7331_QTW/QTW/Will/cherry")

## Load the mens tables
load(file = "CBMenTextTables.rda")
print("List menTables read in")

## Load the womens tables
load(file = "CBWomenTextTables.rda")
print("List womenTables read in")
```

```{r}

menResMat = sapply(menTables, extractVariables)
menDF = mapply(createDF, menResMat, year = 1999:2012,
               sex = rep("M", 14), SIMPLIFY = FALSE)
print("done")

```

```{r}
#options(error=recover)
womenResMat = sapply(womenTables, extractVariables)
womenDF = mapply(createDF, womenResMat, year = 1999:2012,
               sex = rep("F", 14), SIMPLIFY = FALSE)
#test <- extractVariables(womenTables$"2001")
#head(test)
```

```{r}
lapply(womenDF, head)
```
```{r}
lapply(womenDF, tail)
```
```{r}
lapply(menDF, head)
```
```{r}
lapply(menDF, gg_miss_var)
```
```{r}
lapply(menDF, head)
```

```{r}

combined <- bind_rows(menDF)
gg_miss_var(combined)

```

```{r}

combinedW <- bind_rows(womenDF)
gg_miss_var(combinedW)

```